"""add verification status to file_versions

Revision ID: c20590879e63
Revises: d0214aa5f2e0
Create Date: 2026-10-04 23:38:50.492766

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c20590879e63'
down_revision = 'd0214aa5f2e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('verification_status', sa.String(length=16), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.drop_column('verification_status')
        batch_op.drop_column('last_verified_at')

    # ### end Alembic commands ###
