"""add is_encrypted to file_versions

Revision ID: d0214aa5f2e0
Revises: 1b25f9dcc42b
Create Date: 2026-10-04 17:59:59.648440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd0214aa5f2e0'
down_revision = '1b25f9dcc42b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_encrypted', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('file_versions', schema=None) as batch_op:
        batch_op.drop_column('is_encrypted')

    # ### end Alembic commands ###
